name: HugoChecker
description: Check all the hugo files based on the hugo-checker.yaml file
author: ChrisPrusik
inputs:
  hugo-folder:
    required: true
    description: Path to the folder with all hugo files
    default: C:\inetpub\wwwroot
  chatgpt-api-key:
    required: false
    description: API key for chatgpt
    default: 0
runs:
  using: 'node20'
  main: 'index.js'