name: HugoChecker
description: Check all the hugo files based on the hugo-checker.yaml file
author: ChrisPrusik
inputs:
  hugo-folder:
    required: true
    description: Path to the folder with all hugo files
    default: C:\inetpub\wwwroot
runs:
  using: 'node12'
  main: 'index.js'